name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up zig
      - uses: mlugg/setup-zig@v1
        with:
          zig-version: 0.14.0

      - name: Run tests
        run: zig build test

      - name: Check formatting
        run: zig fmt --check .
